version: '3.7'

x-anchors:
  args: &current-user-info
    user: ${USER:-user1}
    user_id: ${USER_ID:-1000}
    group_id: ${GROUP_ID:-1000}

# Settings and configurations that are common for all containers

services:
  nginx:
    image: nginx:1.18-alpine
    ports:
    - "80:80"
    - "4443:443"
    # - "9000:9000"
    # - "9001:9001"
    # - "8001:8000"
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d:ro
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./certbot/conf:/etc/letsencrypt
     - ./certbot/www:/var/www/certbot
    networks:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.1.0/28

